# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_proposal_information_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_proposal_information_widget(object):
    def setupUi(self, proposal_information_widget):
        proposal_information_widget.setObjectName("proposal_information_widget")
        proposal_information_widget.resize(422, 87)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(proposal_information_widget.sizePolicy().hasHeightForWidth())
        proposal_information_widget.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(proposal_information_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.proposal_id_edit = QtWidgets.QLineEdit(proposal_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.proposal_id_edit.setFont(font)
        self.proposal_id_edit.setObjectName("proposal_id_edit")
        self.gridLayout.addWidget(self.proposal_id_edit, 0, 1, 1, 1)
        self.beamtime_id_edit = QtWidgets.QLineEdit(proposal_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.beamtime_id_edit.setFont(font)
        self.beamtime_id_edit.setObjectName("beamtime_id_edit")
        self.gridLayout.addWidget(self.beamtime_id_edit, 1, 1, 1, 1)
        self.start_data_time_edit = QtWidgets.QDateTimeEdit(proposal_information_widget)
        self.start_data_time_edit.setObjectName("start_data_time_edit")
        self.gridLayout.addWidget(self.start_data_time_edit, 2, 1, 1, 1)
        self.proposal_name_edit = QtWidgets.QLineEdit(proposal_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.proposal_name_edit.setFont(font)
        self.proposal_name_edit.setObjectName("proposal_name_edit")
        self.gridLayout.addWidget(self.proposal_name_edit, 0, 4, 1, 1)
        self.proposal_id_label = QtWidgets.QLabel(proposal_information_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proposal_id_label.sizePolicy().hasHeightForWidth())
        self.proposal_id_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.proposal_id_label.setFont(font)
        self.proposal_id_label.setObjectName("proposal_id_label")
        self.gridLayout.addWidget(self.proposal_id_label, 0, 0, 1, 1)
        self.beamtime_id_label = QtWidgets.QLabel(proposal_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.beamtime_id_label.setFont(font)
        self.beamtime_id_label.setObjectName("beamtime_id_label")
        self.gridLayout.addWidget(self.beamtime_id_label, 1, 0, 1, 1)
        self.end_data_label = QtWidgets.QLabel(proposal_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.end_data_label.setFont(font)
        self.end_data_label.setObjectName("end_data_label")
        self.gridLayout.addWidget(self.end_data_label, 2, 2, 1, 1)
        self.end_data_time_edit = QtWidgets.QDateTimeEdit(proposal_information_widget)
        self.end_data_time_edit.setObjectName("end_data_time_edit")
        self.gridLayout.addWidget(self.end_data_time_edit, 2, 3, 1, 2)
        self.start_data_label = QtWidgets.QLabel(proposal_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.start_data_label.setFont(font)
        self.start_data_label.setObjectName("start_data_label")
        self.gridLayout.addWidget(self.start_data_label, 2, 0, 1, 1)
        self.proposal_name_label = QtWidgets.QLabel(proposal_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.proposal_name_label.setFont(font)
        self.proposal_name_label.setObjectName("proposal_name_label")
        self.gridLayout.addWidget(self.proposal_name_label, 0, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)

        self.retranslateUi(proposal_information_widget)
        QtCore.QMetaObject.connectSlotsByName(proposal_information_widget)

    def retranslateUi(self, proposal_information_widget):
        _translate = QtCore.QCoreApplication.translate
        proposal_information_widget.setWindowTitle(_translate("proposal_information_widget", "Proposal Information"))
        self.proposal_id_label.setText(_translate("proposal_information_widget", "Proposal ID"))
        self.beamtime_id_label.setText(_translate("proposal_information_widget", "Beamtime ID"))
        self.end_data_label.setText(_translate("proposal_information_widget", "End Date"))
        self.start_data_label.setText(_translate("proposal_information_widget", "Start Date"))
        self.proposal_name_label.setText(_translate("proposal_information_widget", "Proposal Name"))
