# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_sample_information_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sample_information_widget(object):
    def setupUi(self, sample_information_widget):
        sample_information_widget.setObjectName("sample_information_widget")
        sample_information_widget.resize(420, 70)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(sample_information_widget.sizePolicy().hasHeightForWidth())
        sample_information_widget.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(sample_information_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.sample_name_label = QtWidgets.QLabel(sample_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.sample_name_label.setFont(font)
        self.sample_name_label.setObjectName("sample_name_label")
        self.gridLayout.addWidget(self.sample_name_label, 0, 0, 1, 1)
        self.gap_label = QtWidgets.QLabel(sample_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.gap_label.setFont(font)
        self.gap_label.setObjectName("gap_label")
        self.gridLayout.addWidget(self.gap_label, 1, 2, 1, 1)
        self.gap_edit = QtWidgets.QLineEdit(sample_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.gap_edit.setFont(font)
        self.gap_edit.setObjectName("gap_edit")
        self.gridLayout.addWidget(self.gap_edit, 1, 3, 1, 1)
        self.sample_name_edit = QtWidgets.QLineEdit(sample_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.sample_name_edit.setFont(font)
        self.sample_name_edit.setObjectName("sample_name_edit")
        self.gridLayout.addWidget(self.sample_name_edit, 0, 1, 1, 1)
        self.distance_edit = QtWidgets.QLineEdit(sample_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.distance_edit.setFont(font)
        self.distance_edit.setObjectName("distance_edit")
        self.gridLayout.addWidget(self.distance_edit, 1, 1, 1, 1)
        self.energy_edit = QtWidgets.QLineEdit(sample_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.energy_edit.setFont(font)
        self.energy_edit.setObjectName("energy_edit")
        self.gridLayout.addWidget(self.energy_edit, 0, 3, 1, 1)
        self.energy_label = QtWidgets.QLabel(sample_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.energy_label.setFont(font)
        self.energy_label.setObjectName("energy_label")
        self.gridLayout.addWidget(self.energy_label, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(19, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.distance_label = QtWidgets.QLabel(sample_information_widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.distance_label.setFont(font)
        self.distance_label.setObjectName("distance_label")
        self.gridLayout.addWidget(self.distance_label, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)

        self.retranslateUi(sample_information_widget)
        QtCore.QMetaObject.connectSlotsByName(sample_information_widget)

    def retranslateUi(self, sample_information_widget):
        _translate = QtCore.QCoreApplication.translate
        sample_information_widget.setWindowTitle(_translate("sample_information_widget", "Sample Information"))
        self.sample_name_label.setText(_translate("sample_information_widget", "Sample name"))
        self.gap_label.setText(_translate("sample_information_widget", "Gap"))
        self.energy_label.setText(_translate("sample_information_widget", "Energy"))
        self.distance_label.setText(_translate("sample_information_widget", "Distance"))
